- name: configuring MongoDB server
  hosts: mongodb
  become: yes
  tasks:
  - name: copying MongoDB repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
    register: command_output
  
  - name: print the command output
    ansible.builtin.debug:
      msg: "{{ command_output }}"

  - name: Install MongoDB server
    ansible.builtin.dnf:
      name: mongodb-org
      state: present 



