- name: Configure MySQL Component
  hosts: mysql
  become: yes
  tasks:

    - name: Install MySQL server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: Start and enable MySQL service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Check if MySQL root password works
      ansible.builtin.shell: |
        mysql -u root -p'RoboShop@1' -e "SELECT 1;" >/dev/null 2>&1
      register: root_pass_check
      ignore_errors: yes
      changed_when: false

    - name: Debug root password check
      ansible.builtin.debug:
        msg: "MySQL root password check RC = {{ root_pass_check.rc }}"

    - name: Set MySQL root password if not set
      community.mysql.mysql_user:
        login_user: root
        login_password: ''
        user: root
        host_all: yes
        password: 'RoboShop@1'
        state: present
      when: root_pass_check.rc != 0
