- name: Configure MySQL component
  hosts: mysql
  become: yes
  tasks:
  - name: Install MySQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: present

  - name: Start & enable MySQL service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Install PyMySQL library for MySQL modules
    ansible.builtin.pip:
      name: PyMySQL
      executable: pip3

  - name: Check if shipping user exists (without changing anything)
    community.mysql.mysql_user:
      login_user: root
      login_password: 'RoboShop@1'
      name: shipping
      host: localhost
      state: present
    check_mode: yes
    register: shipping_user_check

  - name: Debug output for shipping user check
    ansible.builtin.debug:
      msg: >
        Shipping user exists? {{ shipping_user_check.changed == false }}

  - name: Create shipping user if not exists
    community.mysql.mysql_user:
      login_user: root
      login_password: 'RoboShop@1'
      name: shipping
      password: 'Shipping@1'
      host: localhost
      state: present
      priv: "*.*:ALL"
    when: shipping_user_check.changed
