- name: configure MySQL component
  hosts: mysql
  become: yes
  tasks:
  - name: install MySQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: installed
  
  - name: Start & Enable MySQL Service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  
  - name: Check if MySQL shipping user password is already set
    ansible.builtin.shell: |
      mysql -ushipping -pRoboShop@1 -e "SELECT User FROM mysql.user WHERE User='shipping';"
    register: mysql_shipping_pass_check
    ignore_errors: yes
    changed_when: false

  - name: Debug output for MySQL shipping user password check
    ansible.builtin.debug:
      msg: >
        MySQL shipping user password check result:
        total output={{ mysql_shipping_pass_check }},
        rc={{ mysql_shipping_pass_check.rc }},
        stdout='{{ mysql_shipping_pass_check.stdout }}',
        stderr='{{ mysql_shipping_pass_check.stderr }}'

  - name: Set MySQL shipping user password (only if check fails)
    ansible.builtin.shell: >
      mysql_secure_installation --set-root-pass RoboShop@1
    when: mysql_shipping_pass_check.rc != 0
