- name: Configure MySQL component
  hosts: mysql
  become: yes
  tasks:
  - name: Install MySQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: present

  - name: Start & enable MySQL service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Check if shipping user exists
    community.mysql.mysql_user_info:
      login_user: root
      login_password: 'RoboShop@1'
    register: shipping_user_info

  - name: Debug output for shipping user check
    ansible.builtin.debug:
      msg: "{{ shipping_user_info.users | selectattr('user','equalto','shipping') | list }}"

  - name: Create shipping user if not exists
    community.mysql.mysql_user:
      login_user: root
      login_password: 'RoboShop@1'
      name: shipping
      password: 'Shipping@1'
      host: localhost
      state: present
      priv: "*.*:ALL"
    when: shipping_user_info.users | selectattr('user','equalto','shipping') | list | length == 0