- name: configure MySQL component
  hosts: mysql
  become: yes
  tasks:
  - name: install MySQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: installed
  
  - name: Start & Enable MySQL Service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Check if MySQL root password is already set
    ansible.builtin.shell: |
      mysql -uroot -pRoboShop@1 -e "SELECT User FROM mysql.user WHERE User='root';"
    register: mysql_root_pass_check
    ignore_errors: yes
    changed_when: false
  
  - name: Show MySQL root password check
    ansible.builtin.debug:
      msg: "MySQL root password check RC={{ mysql_root_pass_check }}"

  - name: Setup root password (only if not set)
    ansible.builtin.shell: >
      mysql_secure_installation --set-root-pass RoboShop@1
    when: mysql_root_pass_check.rc != 0
