- name: Configure MySQL component
  hosts: mysql
  become: yes
  tasks:
  - name: Install MySQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: present

  - name: Start & enable MySQL service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Check if shipping user exists (debug purpose)
    community.mysql.mysql_user:
      login_user: root
      login_password: 'RoboShop@1'
      name: shipping
      host: localhost
      state: present
      priv: "*.*:ALL"
    check_mode: yes
    register: shipping_user_check

  - name: Debug output for shipping user check
    ansible.builtin.debug:
      msg: >
        Shipping user already exists? {{ shipping_user_check.changed == false }}

  # - name: Set MySQL shipping user password (only if not set)
  #   community.mysql.mysql_user:
  #     login_user: root
  #     login_password: 'RoboShop@1'
  #     name: shipping
  #     password: 'Shipping@1'
  #     host: localhost
  #     state: present
  #     priv: "*.*:ALL"
  #   when: shipping_user_check.changed
