- name: configure MySQL component
  hosts: mysql
  become: yes
  tasks:
  - name: install MySQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: installed
  
  - name: Start & Enable MySQL Service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Check if MySQL root password is already set
    ansible.builtin.shell: >
      mysql -uroot -pRoboShop@1 -e "SELECT 1;" 2>/dev/null || echo "password_not_set"
    register: mysql_password_check
    changed_when: false

  - name: Debug MySQL password check result
    ansible.builtin.debug:
      msg: "MySQL root password check result: {{ mysql_password_check.stdout }}"

  - name: Set MySQL root password if not set
    ansible.builtin.command: >
      mysql_secure_installation --set-root-pass RoboShop@1
    when: "'password_not_set' in mysql_password_check.stdout"
  
  # - name: setup root password
  #   ansible.builtin.command: >
  #     mysql_secure_installation --set-root-pass RoboShop@1