- name: configure shipping component
  hosts: shipping
  become: yes
  tasks:
  - name: install maven
    ansible.builtin.dnf:
      name: maven 
      state: installed
  
  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app
  
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Download the application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip
  
  # This module thinks file exists on ansible control server, needs to extract on to remote machine(shipping)
  # remote_src: yes means file already exits in shipping server
  - name: extract the code 
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: install mavn dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app